from github_webhooks import constants


def test_events_values() -> None:
    assert constants.Events.values() == [
        "check_run",
        "check_suite",
        "commit_comment",
        "content_reference",
        "create",
        "delete",
        "deploy_key",
        "deployment",
        "deployment_status",
        "fork",
        "github_app_authorization",
        "gollum",
        "installation",
        "installation_repositories",
        "issue_comment",
        "issues",
        "label",
        "marketplace_purchase",
        "member",
        "membership",
        "meta",
        "milestone",
        "organization",
        "org_block",
        "package",
        "page_build",
        "ping",
        "project_card",
        "project_column",
        "project",
        "public",
        "pull_request",
        "pull_request_review",
        "pull_request_review_comment",
        "push",
        "release",
        "repository_dispatch",
        "repository",
        "repository_import",
        "repository_vulnerability_alert",
        "security_advisory",
        "sponsorship",
        "star",
        "status",
        "team",
        "team_add",
        "watch",
    ]
